name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Set up .env file
        run: |
          echo "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      - uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache node_modules 📦
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies 👨🏻‍💻
        id: pnpm-install
        run: pnpm install

      - name: Run linter 👀
        run: pnpm lint

      - name: Build
        run: pnpm run build
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'

      - name: Get release dir path
        id: release-dir-path
        run: |
          dir=${{ secrets.ROOT_DIR }}/releases/$(TZ=Asia/Shanghai date +%Y%m%d_%H%M%S)
          echo "dir=$dir" >> $GITHUB_OUTPUT

      - name: Generate SHA256 for dist
        run: |
          tar -czf dist.tar.gz -C dist .
          sha256sum dist.tar.gz > dist/SHA256SUM.txt

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        with:
          flags: '-avzr'
          options: ''
          src: 'package.json pnpm-lock.yaml dist'
          dest: 'root@${{ secrets.SSH_HOST }}:${{ steps.release-dir-path.outputs.dir }}'

      - name: Install dependencies and run on server
        uses: appleboy/ssh-action@master
        id: create-release-dir
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: root
          port: 22
          script: |
            bash ${{ secrets.ROOT_DIR }}/scripts/deploy.sh

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been builded.'
